---
title: "Estimates for Poland"
description: |
  Identifying changes in the reproduction number, rate of spread, and doubling time during the course of the COVID-19 outbreak whilst accounting for potential biases due to delays in case reporting in Poland.
bibliography: library.bib
output:
  distill::distill_article:
    self_contained: true
    toc: true
    toc_depth: 3
---




```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 12, 
                      fig.width = 12,
                      dpi = 320)
```


```{r load-packages, include = FALSE}
library(EpiNow)
library(dplyr)
library(rmarkdown)
library(here)
```


## National summary

```{r}
## Control parameters for region-report
summary_tables <- 0
summary_figures <- 0
title_depth <- 3
index <- 1
region <- "poland"
path <- "_posts/global"
show_title <- FALSE
```

```{r,  child = "../../templates/_region-report.Rmd"}
```

